### ISSUE TITLE
Does not work with python 3.10

### ISSUE THREAD

**Issue by vdijken** [linuxmint/mintinstall#349]
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 16, in <module>
    import requests
  File "/home/vdijken/.local/lib/python3.10/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/home/vdijken/.local/lib/python3.10/site-packages/requests/utils.py", line 29, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/home/vdijken/.local/lib/python3.10/site-packages/requests/cookies.py", line 174, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by mtwebster** [comment]
Which Mint version? It works fine on 3.10 on Mint 21.

Do you have a different version of requests installed via pip? If so, remove it and make sure `python3-requests` is installed.

```
$ apt policy python3-requests
python3-requests:
  Installed: 2.25.1+dfsg-2
  Candidate: 2.25.1+dfsg-2
```

You shouldn't mix pip with system packages. Make a sandboxed install for python if you need newer versions of modules. At the very least only install pip packages for which a system equivalent isn't currently installed (system-provided modules always begin with `python3-`).
